import React from 'react'
import devburger1 from '../../assets/imagens/devburger (1).jpg'
import devburger2 from '../../assets/imagens/devburger (2).jpg'
import devburger3 from '../../assets/imagens/devburger (3).jpg'
import devburger4 from '../../assets/imagens/devburger (4).jpg'
import devburger5 from '../../assets/imagens/devburger (5).jpg'
import devburger6 from '../../assets/imagens/devburger (6).jpg'
import devburger7 from '../../assets/imagens/devburger (7).jpg'
import devburger8 from '../../assets/imagens/devburger (8).jpg'
import devburger9 from '../../assets/imagens/devburger (9).jpg'
import devburger10 from '../../assets/imagens/devburger (10).jpg'
import devburger11 from '../../assets/imagens/devburger (11).jpg'
import devburger12 from '../../assets/imagens/devburger (12).jpg'
import devburger13 from '../../assets/imagens/devburger (13).jpg'
import devburger14 from '../../assets/imagens/devburger (14).jpg'
import devburger15 from '../../assets/imagens/devburger (15).jpg'

export const burger1 = [devburger1, devburger2, devburger3, devburger4 ,devburger5, devburger6, devburger7, devburger8, devburger9, devburger10, devburger11, devburger12, devburger13, devburger14, devburger15]